apiVersion: v1
kind: Secret
metadata:
  name: fast-food-totem-api-secret
type: Opaque
data:
  ConnectionStrings__SqlServerConnection: 'U2VydmVyPW15ZGIuY2htaWNvaXlnajd0LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbSwxNDMzO0RhdGFiYXNlPUZhc3RGb29kVG90ZW07VXNlcj1kYnVzZXI7UGFzc3dvcmQ9ZGJwYXNzd29yZDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWU7' 
  MercadoPago__AccessToken: "VEVTVC03NTIyNjU3OTAwNzQ1MzQtMTAxMjE1LTBlNTg3MjlkMDdjNTZkNmZkYWNkOTJhNTE1Y2RhZGFkLTY4OTYwMjcw"
  MercadoPago__BaseUrl: "aHR0cHM6Ly9hcGkubWVyY2Fkb3BhZ28uY29t"
  MercadoPago__UserId: "Njg5NjAyNzA="
  MercadoPago__ExternalPosId: "MTI="